### PR TITLE
2.6.x slow sync (last updata 2023.11.25)

### PR DESCRIPTION
**Pull request by jzy-chitong56**
**BJ new**
- shared mode（code synchronized to 3.2.2）
- Dialog show Strategy name （code synchronized to 3.2.2）
- BJ dialog code synchronization to 3.2.2
- W3C DenyTip
- BlizzardVAI.eai now can use zoom , but no W3C DenyTip
- Back language
- Surrender switch
- Switch show state on Buttons and Reports

**BJ fix and change**
- BlizzardVAI.eai ai script file read race.txt 1% and 2%
- Fixed all Blizzard player num， 12 / 24  automatic compatibility
- Fixed Second Choose languages cannot take effect
- Introduction to all mode displays
- add max and min zoom tip , zoom distance synchronization to W3C , support input '-zoomxxxx' and '-zoom xxxx' （Preventing non English speaking players will enter spaces） , can be adjusted using the UP and DOWN keys（50 distance 
each time and very poor experience）

----------------------------------------------------------------------------

** DevTools**
- (DevTools) MPQEditor.exe update to 4.0.0.908-en(x64)
- (DevTools) MakeVAIXX.bat Synchronize code for non VS AI scripts, include ROC
- (DevTools) MakeOptROC.bat code synchronization to MakeOptTFT.bat
- (DevTools) Synchronized MakeROC bat file code to MakeXXX.bat
- (DevTools) W3C Item icon and Install tool(InstallROC/TFTtoDir-Icon.pl , the new Install ts file on 3.2.2 ) , old war3 only have item icon , and this icon only compatible with war3 1.35 and below , indeed , writing icon will overwrite the object editor settings , Players must choose their own risks , hope you can give player two optional Package , maybe call 2.x.x W3C item icon(old war3) and 3.x.x W3C icon(1.36+ war3)
- (DevTools) Optimize.bat change imitate MakeAll.bat
- (DevTools) Optimize.bat and MakeAll.bat Final Compilation , Prevent BJ final generation ROC
- (DevTools) Optimize.pl Synchronized to 3.2.2 dev

----------------------------------------------------------------------------
**translation** 
change to uft8
Chinese chat translation adjustment
merged  Russian translation  @Lolasik011
merged  Spanish translation  @Slayer95

----------------------------------------------------------------------------

**CJ new**
- fix hero cannot learning Skills , the bug only on war3 1.30 , but AI Scripts cannot accurately determine version , so fix code will run on 1.29+ all version (BJ can accurately determine version  , no use it's to prevent some players from not installing it) , and this fix can work on all AI , no only amai , for a more fair AMAI VS AI

**CJ change and fix**
- fixed player color
- debugging sharing observer（code synchronized to 3.2.2）
- Fixed duplicate report
- GlobalSettings.txt front_base_distance now is dynamic , first is 1100 , and increase according to AI difficulty , front_base_distance = difficulty * 50 + front_base_distance
- if race no use racial_lumber or race no harvest wood , front_base_distance additional additions 100
- GlobalSettings.txt ver_food_limit now use GetPlayerState(ai_player, PLAYER_STATE_FOOD_CAP_CEILING) , no longer is 100 , and DynamicSystem can keep building unit(I Sceptical)
- ROC use PickMeleeHero choose hero no set neutral hero
- ver_neutral_hero_number Initial value is 0 ，call InitGlobalSettings will set new value , then ohter AI can use PickMeleeHero choose hero , and now ROC still is 0
- GOBLIN_TINKER abnormal skill learning
- fix UPG_BOLT 4-letter-code

### CODE REVIEW

**Comment by SMUnlimited** [comment]
I'm considering setting up a different TFT1.24 in master instead of porting everything back to 2.6.x . That way all the improvements and fixes in master are just available for the older version. This would require the natives and common files to be set by the version which would also fix the ROC build as well. Then use some sort of is legacy flag to enable hacks in 2.6.x branch to support missing newer functions or functionality of warcraft 3.

This will be a lot of work but will probably be more beneficial long term.

**Comment by jzy-chitong56** [comment]
Not very realistic, I have already synchronized the 2.6 code with the main branch，The situation encountered is due to the lack of new interfaces, and some functional parts must be replaced with stupid methods. If it is really implemented, you must point both com.J and B.J to version 1.24 for compilation. 
What's more troublesome is that the technology tree is not only about changing the unit base table and columns，The strategy build sequence also needs to be coordinated and adjusted, that is prepare two copies

Perhaps you can take a look at my 2.6 branch and compare the code differences with 3.2
Alternatively, simply take my branch over to the main branch and rename it to 2.6. When compiling, it points to different folders, but both branches can use the same ROC folder, which is relatively easy

Main differences
- API
- Player limit and Neutral player number
- Technology Tree
- 1.31 Special repair without learning skills

**Comment by jzy-chitong56** [comment]
Maybe before your big project is completed

You can first make some simple fix and update , get old war3 player a new version , like 2.6.2a~z

**Comment by jzy-chitong56** [comment]
The old version is no longer in use, and the fix will be merged into the new version, which will be adapted and submitted by 1.36.1 at a later time

**Pull request closed without merging**
