### PR TITLE
Implement transfer to neutral victim on surrender and set as default

### PR DESCRIPTION
**Pull request by Slayer95**

### CODE REVIEW

**Comment by SMUnlimited** [comment]
This sounds good, but doesn't look like it will compile because bj_PLAYER_NEUTRAL_VICTIM_AMAI variable doesn't exist in REFORGED, so needs the additional definition into custom_common.eai.

**Comment by Slayer95** [comment]
Alright, @SMUnlimited . It doesn't look like I need to mess with ``ForwardsCompat.bat``, do I?

**Comment by SMUnlimited** [comment]
With how you done it, no shouldn't need to touch FowardsCompat

**Comment by jzy-chitong56** [comment]
how about use `sharedRacePlayer`
when not race player , use this share to NEUTRAL_VICTIM
@SMUnlimited

**Comment by Slayer95** [comment]
@jzy-chitong56  this change only affects cases in which AMAI has no allies.

**Pull request merged**
