### PR TITLE
Feature/electron amai

### PR DESCRIPTION
**Pull request by paulo101977**
Starting the builder with Electron (install, compile, manage profile, etc.)

### CODE REVIEW

**Comment by SMUnlimited** [comment]
This is very welcome work since the old UI stopped working. Once you have completed, this will help address #64

**Comment by paulo101977** [comment]
> This is very welcome work since the old UI stopped working. Once you have completed, this will help address #64

I'm finishing at least the process of installing AMAI on maps, in order to release it. Oh, and also add a note in the README on how to use and install it for development purposes.

**Comment by paulo101977** [comment]
I ended up with the installation process in a specific directory and map. Next step I think will be compiling and compiling with optimization.

**Review by paulo101977 — COMMENTED** [review]
I ended up with the installation process in a specific directory and map. Next step I think will be compiling and compiling with optimization.

**Review by paulo101977 — COMMENTED** [review]
finalizing the changes

**Pull request merged**
