### PR TITLE
Slow sync - B.J adjustment v2

### PR DESCRIPTION
**Pull request by jzy-chitong56**
**change**
 - (DevTools) Now can set back language to not English , and synchronize from B.J to C.AI during initialization
   - _elseif cmd == 72 then // change backlanguage_ , the code maybe should merge to cmd 71 , this increases the number of rows too much , but I don't have a good idea

-  (DevTools) Surrender can be set on the console , is independent switch (I did see some players suggesting that AI should not commit suicide)
   - _no human mode_ and _shared mode_ will close surrender , because human people have not units and only rely on AI , especially shared mode , **Hang on , can win**
   -  differ in disable_surrender  , surrender_allowed after closing , the suicide detection job will not be triggered 

- Console switch now can show state on Buttons and Reports , but need help : https://github.com/SMUnlimited/AMAI/issues/178
   - (DevTools) Set switch status initial values on Commands.txt **Dialog Text3** -- **on**/**off** or **arr on**/**off**  ( _main switch or person switch_ )
   - Note: B.J unable to obtain C.AI switch status , but all switch status based on C.AI , so developers must synchronize initial values
   - Note: button only show main switch status , not player person switch status
   - Note: include show DEBUG and BALANCE switch , **maybe you don't want to show this , or only show when just have one human player**
   - _Note: To better display the switch status ，I changed the chat report（Commands.txt）, But I didn't modify other language _
 
- initLanguage%1 not need save back language , this is redundant , because all languages will initialized
   - Note: maybe use language replacing the hash table would be better , record the backup language first, and then replace it with the actual language
_#INCLUDETABLE <Languages\eng\CommandsTrans.txt> #ENC:%4 #EFR
  call SaveStr(translation, StringHash(language), StringHash("%1"), "%2")
#ENDINCLUDE
#INCLUDETABLE <Languages\%1\CommandsTrans.txt> #ENC:%4 #EFR
  call SaveStr(translation, StringHash(language), StringHash("%1"), "%2")
#ENDINCLUDE_

- More job move to path system when path done , help job system more focused on combat （**_Please review this modification for suitability and assess the risks_**）
   - (DevTools) because some job run on path system , no longer possible to disable all JOB without running job system , so add a switch -- **job_running** , this can shut down job system all job , just need set to false
   - Note: running on path system'job , they self running cycle may be slightly adjusted , because it's impossible to balance using 'second' and 'sleep_multiplier' two units of calculation
   - Note: this will indirectly strengthen AI , because the interval between JOBs has actually been shortened
   - Note: because shortened the interval , the code that traverses units will run frequently, and if a large number of units gather (such as 1V23 or 4v20), it will cause the game to latency(FPS become 0) earlier
   - Note: here no use like TQRemoveRoot , because it feels like complicated to run , **hope you can help optimized code**

- More functions do not use local variables to return (not yet fully processed)

- StartExpansionAM will intervene expansion priority , ensure expansion when not mine but have rescources
   - fix exp peon unit  unfixed , must be like build_zeppelin to ensure successful mining, especially in the later stages of the game ， AI often there are no gold mines, but there are still idle gold mines on the map

- GetLocationEnemyStructures change to GetLocationEnemyStrength , add boolean only_structures use to distinguish only check structures or include structures , _because GetLocationNonCreepStrength no take Structures and GetLocationEnemyStructures only take Structures , if take all Strength need run two function_

- BuyAllyShopItem not take hidden unit

- GetBuildingBuilt not take hidden and die unit

- MILITIA_EXPAND job no longer only run once , but only running on one or no mine

- optimize Save Yourself Mode code

- optimize ancient_exp_unit move , tree move speed always not 0 , even if root

- FocusFire code optimize

**fix**
- fix harvesting ghouls unable to take effect ,  setup_force always send all quantities , so FormGroupAM still a probability of triggering all quantities
- fix GroupOrderFocusWindInstant_d processing RESET_WINDWALKER job logic , should run job when send order , not add windwalk_group groud
- fix GroupOrderAttack_d no RecycleGuardPosition
- fix FocusGroupRemoveGuard endless loop
- fix BuyNeutral defined local variables retreat_home
- fix UPG_BOLT 4-letter-code
- fix Cache cleared , if Cache , ai name will repeat
- fix https://github.com/SMUnlimited/AMAI/issues/190

**optimized code**
- BR build

**fragmented thoughts**
- now have some temporary processing , mainly for code adaptation: handling returns without using local variables , and the buy and focusfire job will be submitted for unified code optimization and change at a future time

- W3C give Observer initial new zoom and it has not been removed yet , Maybe need consider about
https://github.com/w3champions/map-updater-scripts/blob/45ca3c939d84480e13b93f5f90abe596a4f1a4f8/src/player_features/zoom.ts#L21

- B.J should need to submit again （add W3C deny unit tip） when submit deny unit at a future time （if you consider ）

- GroupMicroSystem looks like there's a problem , the code control unit movement ,  but micro_ranged_group filter ally players , this will control other players , perhaps at least human players need to be excluded

- https://github.com/SMUnlimited/AMAI/issues/18 ，now have some fix , because now can randomly send unit to different bases （But this code seems to have a problem , I need to test it again）, if you still worried that AI just one base or save unit to much on one base （Maybe bad luck or the army was defeated） , you can copy **patrol order** code （in your fountain save unit job） to send_home job 

- sfmpq-license.txt ,SFmpq.dll and empty.mpq should also belong to the old installer file should be removed

- SplitBlizzardJ.pl will create multiple BlizzardN.J , but this file for compilation only , perhaps it can be automatically cleaned up after compilation is completed ?

- IsStandardUnit not need all unit check unit_zepplin_move and unit_rescueing , only  zepplin will add this group（perhaps this should become a rule)

- 1.36.1 ptr function code remains unchanged 

- 2.6.x , should use which technology tree ， maybe should give setting , developer just need add StandardUnits_ver.txt , let MakeTFTBase.bat setting ， and  BuildSequence.ai give a **non random reveal all the details technology research code**  like official AI

```
SET VER=24
ECHO Making AMAI
ECHO _____________________________
if %VER% == 24 perl ejass.pl TFT\StandardUnits1.24.txt TFT VER:TFT > TFT\StandardUnits.txt
if %VER% == 29 perl ejass.pl TFT\StandardUnits1.29.txt TFT VER:TFT > TFT\StandardUnits.txt
```

- 1.31 really can be played ROC , here have picture , not just the entrance , game can be run
https://user-images.githubusercontent.com/48715223/265273484-b0514a64-7625-4f46-86ca-fa818aeeb2f1.jpeg

### CODE REVIEW

**Comment by SMUnlimited** [comment]
Merged the optimizations and fixes part of this PR: https://github.com/SMUnlimited/AMAI/pull/185

But the job system and blizzard.j changes I haven't included as yet as will need more thought.
Job split doesn't bring much advantage at the moment as there isn't job congestion to cause a notable impact. 
Would rather use it for slow jobs or need to use a sleep, but that control should be by the job configuration rather than hardcoded.

**Comment by jzy-chitong56** [comment]
Considering that different threads are allocated, theoretically it can be executed simultaneously. 
The job system will sleep after each execution,This situation will cause an increasing delay during work congestion, such as having 10 units to check save job，At this point, the delay will be visible to the naked eye

Another issue ，Will there be any issues when different threads simultaneously call the same function，I bet it wouldn't be so coincidental, so I changed it this way

Perhaps you should point out whether my instructions were translated correctly, and whether the instructions about changes need to indicate the number of files and code lines again. This may be more effective than workflow, as I will add modifications after submitting the pull，This bad problem has never been corrected

**Comment by SMUnlimited** [comment]
Makes sense that a thread controls all the unit micro separately to other jobs, as unit micro will scale the most as number of players and units increase.

There is a risk with multiple threads interacting with the same function if they modify the same variables as then things can get out of sync during operation which could lead to weird bugs,

In terms of pull requests, if they are individual functionality of separate concerns rather than one massive PR with lots of changes its easier to spot instructions or questions and review faster. This PR could have been 5 different PR's e.g One PR adds the job system in the pathing thread, Another PR adds the back language button, one PR for optimizations, one of expansion improvements, one for minor fixes etc

**Comment by jzy-chitong56** [comment]
In fact, I did not differentiate by function, but only estimated the submission volume based on the approximate number of modified lines. There are indeed many modules involved, perhaps just submitting one module at a time and adding fixes is enough

**Comment by jzy-chitong56** [comment]
today fix  back language

**Comment by jzy-chitong56** [comment]
Close pull and continue processing with new pull to avoid reading difficulties caused by outdated code

**Pull request closed without merging**
