### PR TITLE
Install Manager Multilingual

### PR DESCRIPTION
**Pull request by jzy-chitong56**
Multilingual adaptation of the **Install Manager** 
 - Automatically obtain browser language , this means I didn't test English , but there is a fault tolerance mechanism, and the default language will be set back to English
 - Currently supports both English and Chinese , **But there is no proactive change function provided**
 - The structure of the language text has been established and can be translated using English as a template

New UI
 - If you want to use the Manager to handle **StrategityManager** functionality, **this UI may not be suitable**
 - winodws there is a minimum size available
 - **Wallpaper** and its features have been replaced
 - The **original menu** has been adjusted
 - The interaction between disabling during installation and restoring after installation, which is the same as the menu, is also supported
 - The pictures and styles may be ugly, it's best to make changes , If possible, please replace the image with a separate image and text. There are still some text on it that can be translated
 - The replacement of the title bar icon file does not seem to take effect, so I have reserved a new ICON file. Perhaps you can check the problem

Known issues
 - I have followed the original code structure as much as possible for all the code （At least I think so）, but the code inside each file is very poor because it is integrated from several AI Q&A, and only meets the requirements for work 
 - **Install.js** unable to multilingualize ，I don't know how to get variables when passing in information. Even if I cut them, the main process needs to pass in too many variables, which is not easy to **main.ts**. However, finding the corresponding JS file（like Install_cn.js , Install_en.js） based on the language requires more maintenance. Nevertheless, I still established a translation text for the installation log
 - remove `reload` menu , I suspect that you forgot to modify it here, which has caused this feature to remain unusable, but I don't want to test this part and just removed it , Translation does not include `reload`
```
    // hot reload frontend
    require('electron-reloader')(module);
    win.loadURL('http://localhost:4200');
```

------------------------------------------------------------------------------------------------------
I'm not sure what I said, all the text here is translated and may not be very accurate

 https://github.com/SMUnlimited/AMAI/issues/209

### CODE REVIEW

**Comment by paulo101977** [comment]
@jzy-chitong56 We use Angular as a framework on the front, so the translation is normally performed via extract-i18n: https://angular.io/guide/i18n-common-translation-files
This automatically generates translation files and at the same time changes variable values ​​during translation.

**Comment by jzy-chitong56** [comment]
@paulo101977 I work directly using the web version of Git and don't know how to run the console, let alone install the work environment. 
My understanding is that this program will automatically create a tree directory, which is much more standardized than what I manually maintain. However, accurate translation still requires manual proofreading. 
I don't know if there are any other inaccuracies besides this, and if this translation tool is used, the translation of the main process can directly write variables, Do no longer need send translated text from the rendering process?

**Comment by paulo101977** [comment]
> I work directly using the web version of Git and don't know how to run the console, let alone install the work environment.
> My understanding is that this program will automatically create a tree directory, which is much more standardized than what I manually maintain. However, accurate translation still requires manual proofreading.
> I don't know if there are any other inaccuracies besides this, and if this translation tool is used, the translation of the main process can directly write variables, Do no longer need send translated text from the rendering process?

I didn't try to run the process, I just looked at the code. But I believe that if everything is ok, I don't see any problems with the translation. I just pointed out a more common tool for angular. And yes, more accurate translations must be done manually for each language (unless we use some AI algorithm to do the automatic translation).

**Comment by jzy-chitong56** [comment]
What I am concerned about is the illegal code structure, as it only works after packaging. You can find attachments in my workflow to verify if the application works. However, I would prefer you to see issues with the code, such as style, page, process, etc. If you could help me adjust the aesthetics of the page, that would be great

**Comment by SMUnlimited** [comment]
Pulled in the UI part of this PR. But need to look into angular extract-i18n for localization before merging the rest. I've enabled the angular localization library in package.json which was missing but needs more investigation.

**Comment by jzy-chitong56** [comment]
image

I suspect that the problem lies in these locations. I don't know when the text was uniformly replaced. It may be because the modified code was uploaded after a failed local compilation. After researching CI, I stopped tinkering with the local environment and never made any changes back. I'm sorry, it increased your workload

**Comment by jzy-chitong56** [comment]
I didn't know about this module  -- **localize** 
I wrote very unprofessional

**Comment by jzy-chitong56** [comment]
https://www.yisu.com/jc/843209.html
maybe no need `angular extract-i18n`

Slightly simpler, as you have already used `JOSN` to configure localization
Instead of `XLF`

**Comment by jzy-chitong56** [comment]
`Electron\app package.json package-lock.json`
Perhaps these modules need to be enabled here as well

**Comment by paulo101977** [comment]
> `Electron\app package.json package-lock.json` Perhaps these modules need to be enabled here as well

package-lock.json should not be changed directly. It is a kind of post-installation cache. It is modified when you do an npm install, etc.

**Comment by SMUnlimited** [comment]
Merged similar changes in the end but a more complete form of this with in app language selection and all our supported languages.

**Pull request closed without merging**
