### PR TITLE
fix ANCIENT_EXPANSION_CHECK can not run and only run once

### PR DESCRIPTION
**Pull request by jzy-chitong56**

### CODE REVIEW

**Comment by SMUnlimited** [comment]
We need to allows repeats when we sure doing the expansion doesn't make them play worse which is what used to happen. 

Also why not just give the heros the rush bonus in standardunits.txt? Looks like they all got set to 0 at some point. But the idea was certain heroes you should do ancient expansion with as its safer while other no need. Can still check all 3 heroes though as that makes sense.

**Comment by jzy-chitong56** [comment]
Because I don't know how to set this `bonus`, and in fact, I don't quite understand the strength value and all core logic. 
Since it has always been 0 and has not been modified in so many versions, there must be a reason. 
It's not suitable to adjust the `bonus` separately according to the version now

Besides, I only noticed the level of `race_ancient-expansion_rero_rush_level`, and subconsciously thought that level was enough

As you said, this action is quite dangerous, but you can take a look at my code. I have rewritten most of the JOB, and I even specifically assigned attack modes（at `Single Melee Attack`） for this extended JOB -- all hero will join ancient-expansion

I think if can be used for ancient  expansion, it would be better than all the trees root to attack in despair

_The current problem with AI is that it can only manipulate ancient trees to automatically root in their original positions. However, once the unroot, the original position is likely to be occupied（RB have this problem）, resulting in the inability to root. In lower versions, it is difficult to determine the status of the tree, making it difficult to handle_

_Of course, this is a continuous process that will take up a lot of your time. I will try my best to submit the content that can be disassembled separately, and only submit it together when it cannot be disassembled, such as the entire JOB file_

**Comment by SMUnlimited** [comment]
Merged via the above commits that tweak to what i mean. Will give it a test and see how it plays becoming active later on.

**Comment by jzy-chitong56** [comment]
This is actually very unreasonable. 
You will find that several functions use `rush bonus`, but `rush bonus` only has one parameter. 
Although you have adjusted `rush bonus` for `ancient expansion`, some hero is not suitable for `ancient expansion`, but he may be suitable for another function. One parameter cannot meet these scenarios , so I almost abandoned this parameter , like `TR race_towerrush_hero_rush_level` 

Perhaps `rush bonus` would be better to calculate based on the overall strength

**Comment by jzy-chitong56** [comment]
I still suggest that cyclic testing can be conducted, and the cycle can be extended
`delete line 31 return`

**Pull request closed without merging**
